<?php
/**
 * Generated by Haxe 4.3.7
 */

namespace wphx\fixtures\wp\core;

use \php\Boot;

class WpdbMysqliGlobalLoweringProofEntry {
	/**
	 * @param \mysqli_result $result
	 *
	 * @return \StdClass
	 */
	public static function fetchObject ($result) {
		#fixtures/wp-core/src/wphx/fixtures/wp/core/WpdbMysqliGlobalLoweringProofEntry.hx:18: characters 3-42
		return \mysqli_fetch_object($result);
	}

	/**
	 * @return void
	 */
	public static function main () {
	}

	/**
	 * @param \mysqli $handle
	 * @param string $query
	 *
	 * @return mixed
	 */
	public static function nativeQuery ($handle, $query) {
		#fixtures/wp-core/src/wphx/fixtures/wp/core/WpdbMysqliGlobalLoweringProofEntry.hx:13: characters 3-43
		return \mysqli_query($handle, $query);
	}
}

Boot::registerClass(WpdbMysqliGlobalLoweringProofEntry::class, 'wphx.fixtures.wp.core.WpdbMysqliGlobalLoweringProofEntry');
